/**
 * Generated by Mavanagaiata at ${TIMESTAMP}
 */

package ${PACKAGE_NAME};

public final class ${CLASS_NAME} {

    public static final String COMMIT_ABBREV = "${COMMIT_ABBREV}";

    public static final String COMMIT_SHA = "${COMMIT_SHA}";

    public static final String DESCRIBE = "${DESCRIBE}";

    public static final boolean DIRTY = ${DIRTY};

    public static final String TAG = "${TAG_NAME}";

    public static final String VERSION = "${VERSION}";

}
